name: Basic Quality Check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count characters
        run: |
          find . -name "*.md" -exec wc -c {} +
